### ISSUE TITLE
java.lang.AssertionError: Wrong line separators: '...ct Now and\r\n     Mid...' at offset 3679

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Windows 10 Home, Version 21H1, OS build 19043.1466, Windows Feature Experience Pack 120.2212.3920.0 (amd64) 
* IDE: WebStorm 2021.2 (build WS-212.4746.80)
* Plugin: 2022.01.05-565
* NodeJS: (installed global) v16.13.2

## Problem description

I was editing my email in the left pane; the right pane showed the rendering. I clicked the "Show HTML" button in the right pane.

## Expected Behavior

I should have seen the HTML version of my email in the right pane.

### Actual Behavior

I have a grey (#f2f2f2) screen in the right pane.

### Steps to Reproduce

as above

### Important Factoids

Maybe this is relevant. My Node v16.13.2 is in C:\Program Files (x86)\nodejs\... When it installed, it also installed NPM 8.1.0 at C:\Program Files (x86)\nodejs\node_modules\npm\... When I updated NPM via "-g", NPM 8.3.2 appeared at C:\Users\G\AppData\Roaming\npm\... (you probably know that directory is a Windows-ism supporting roaming). I configured WebStorm to use the Node v16.13.2 and NPM 8.3.2.

#### StackTrace
```
java.lang.AssertionError: Wrong line separators: '...ct Now and\r\n     Mid...' at offset 3679
at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2512)
at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:710)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:122)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:117)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:108)
at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:123)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.createSourceViewer(MjmlPreviewFileEditor.kt:280)
at de.timo_reymann.mjml_support.editor.ui.MjmlSplitEditor$createViewActionGroup$3.setSelected(MjmlSplitEditor.kt:85)
at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:49)
at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:171)
at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:150)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:150)
at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:427)
at java.desktop/java.awt.Component.processEvent(Component.java:6417)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by timo-reymann** [comment]
Can you please provide a git sample or gist to reproduce this issue? Thanks in advance :)
