### ISSUE TITLE
java.lang.Throwable: Invalid file: file:///Users/vojkan/Code/www/hw/it2/public_html/application/views/email-mjml/_mjml-design-system/company.mjml (invalid)

### ISSUE THREAD

**Issue by vnmilosevic** [timo-reymann/intellij-mjml-support#113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Mac OS X 12.3 (x86_64)
* IDE: PhpStorm 2021.3.2 (build PS-213.6777.58)
* Plugin: 2.0.0

#### StackTrace
```
java.lang.Throwable: Invalid file: file:///Users/vojkan/Code/www/hw/it2/public_html/application/views/email-mjml/_mjml-design-system/company.mjml (invalid)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:356)
at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:154)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.isValidMjmlDocument$lambda-0(MjmlPreviewFileEditor.kt:159)
at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.isValidMjmlDocument(MjmlPreviewFileEditor.kt:157)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.updateHtml(MjmlPreviewFileEditor.kt:196)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.updateHtmlPooled$lambda-7(MjmlPreviewFileEditor.kt:363)
at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
at com.intellij.util.Alarm$Request.runSafely(Alarm.java:385)
at com.intellij.util.Alarm$Request.run(Alarm.java:374)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by timo-reymann** [comment]
Can you please provide more information on how to reproduce?

**Comment by vnmilosevic** [comment]
Hello. I really do not know. It just happened. I moved from one branch to another and an error occurred. I closed the program and restarted and there were no more errors. Maybe it's about upgrading to macOS Monerey 15.3. I'm just guessing.

Vojkan

**Comment by timo-reymann** [comment]
Okay than i will close this for now :D
