### ISSUE TITLE
Plugin crashes after opening mjml file in fresh ide setup

### ISSUE THREAD

**Issue by timo-reymann** [timo-reymann/intellij-mjml-support#2]
**IDE used**
PHPStorm 2020.3.3

**What doesnt work?**
After opening an mjml file the editor crashes/doesnt open

**Reported by**
Stefan Kilp (via Mail)

**Stack-Trace:**
```
java.nio.file.NoSuchFileException: C:\Users\*\*\apps\phpstorm\2019.3.3-193.6494.47\IDE\plugins\mjml-support\renderer.zip
    at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
    at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
    at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
    at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
    at java.base/java.nio.file.Files.copy(Files.java:3142)
    at de.timo_reymann.mjml_support.util.FilePluginUtil.copyFile(FilePluginUtil.kt:14)
    at de.timo_reymann.mjml_support.editor.MjmlJCEFHtmlPanel.copyFiles(MjmlJCEFHtmlPanel.kt:15)
    at de.timo_reymann.mjml_support.editor.MjmlJCEFHtmlPanel.<init>(MjmlJCEFHtmlPanel.kt:11)
    at de.timo_reymann.mjml_support.editor.JCEFHtmlPanelProvider.createHtmlPanel(JCEFHtmlPanelProvider.kt:6)
    at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditor.attachHtmlPanel(MjmlPreviewFileEditor.kt:238)
    at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditor.<init>(MjmlPreviewFileEditor.kt:293)
    at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditorProvider.createEditor(MjmlPreviewFileEditorProvider.kt:23)
    at de.timo_reymann.mjml_support.editor.SplitTextEditorProvider$Companion$getBuilderFromEditorProvider$1.build(SplitTextEditorProvider.kt:97)
    at de.timo_reymann.mjml_support.editor.SplitTextEditorProvider$createEditorAsync$1.build(SplitTextEditorProvider.kt:30)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:891)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:860)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1683)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:859)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:463)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:481)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:858)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:804)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:785)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:785)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:778)
    at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.openFiles(FileDropHandler.java:70)
    at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.handleDrop(FileDropHandler.java:53)
    at com.intellij.openapi.editor.EditorDropHandler.handleDrop(EditorDropHandler.java:31)
    at com.intellij.openapi.editor.impl.EditorImpl.handleDrop(EditorImpl.java:4592)
    at com.intellij.openapi.editor.impl.EditorImpl$MyTransferHandler.importData(EditorImpl.java:4661)
    at java.desktop/javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1544)
    at java.desktop/java.awt.dnd.DropTarget.drop(DropTarget.java:452)
    at java.desktop/javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
    at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547)
    at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:863)
    at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:787)
    at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4621)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4483)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
    at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by timo-reymann** [comment]
Fix:
https://github.com/timo-reymann/intellij-mjml-support/commit/86a502df9662144079548b22efa05ff10150b2b0

**Comment by Ririshi** [comment]
Seems like a similar problem is still occurring for me, related to this issue. See https://github.com/timo-reymann/intellij-mjml-support/issues/8#issuecomment-835201535.

**Comment by timo-reymann** [comment]
So instead of using the plugins home from the platform sdk i now diretctly use the system path for storing configuration: https://github.com/timo-reymann/intellij-mjml-support/commit/aaabd51f663055aca86e29ceb08bda6d57fed57e

This way its always stored in an user writable location, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
