### ISSUE TITLE
Improve handling of mjml errors to prevent uncaught exceptions

### ISSUE THREAD

**Issue by timo-reymann** [timo-reymann/intellij-mjml-support#31]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now there are cases where mjml raises errors to stderr, that are currently leading to uncaught exceptions of the plugin.
After a little discussion in the mjml project it seems this is the intended behaviour and it should be either ignore or handle the stderr in a different way.

The purposed solution would be either
- ignore stderr completely
- write stderr to a custom message in the event log

But in any case it should be handled differently from the stdout as it is right now

### References

* https://github.com/mjmlio/mjml/issues/2310

* stack-trace:

> Error parsing result from stdout: No matching component for tag : mj-s
> {"html":"\n    <!doctype html>\n    <html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com🏢office\">\n      <head>\n        <title>\n          \n        </title>\n        \n        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n        \n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n        <style type=\"text/css\">\n          #outlook a { padding:0; }\n          body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }\n          table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }\n          img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }\n          p { display:block;margin:13px 0; }\n        </style>\n        \n        \n        \n      \n        <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\">\n        <style type=\"text/css\">\n          @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n        </style>\n      \n\n    \n        \n    <style type=\"text/css\">\n      @media only screen and (min-width:320px) {\n        .mj-column-per-100 { width:100% !important; max-width: 100%; }\n      }\n    </style>\n    <style media=\"screen and (min-width:320px)\">\n      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }\n    </style>\n  \n        <style type=\"text/css\">\n        \n\n    .mj-carousel {\n      -webkit-user-select: none;\n      -moz-user-select: none;\n      user-select: none;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-icons-cell {\n      display: table-cell !important;\n      width: 44px !important;\n    }\n\n    .mj-carousel-radio,\n    .mj-carousel-next,\n    .mj-carousel-previous {\n      display: none !important;\n    }\n\n    .mj-carousel-thumbnail,\n    .mj-carousel-next,\n    .mj-carousel-previous {\n      touch-action: manipulation;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-radio:checked + .mj-carousel-content .mj-carousel-image {\n      display: none !important;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-radio-1:checked + .mj-carousel-content .mj-carousel-image-1 {\n      display: block !important;\n    }\n\n    .mj-carousel-previous-icons,\n    .mj-carousel-next-icons,\n    .mj-carousel-8d0f8a46c6d6-radio-1:checked + .mj-carousel-content .mj-carousel-next-1,\n    .mj-carousel-8d0f8a46c6d6-radio-1:checked + .mj-carousel-content .mj-carousel-previous-1 {\n      display: block !important;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-radio-1:checked + .mj-carousel-content .mj-carousel-8d0f8a46c6d6-thumbnail-1 {\n      border-color: #cccccc !important;\n    }\n\n    .mj-carousel-image img + div,\n    .mj-carousel-thumbnail img + div {\n      display: none !important;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-thumbnail:hover + .mj-carousel-main .mj-carousel-image {\n      display: none !important;\n    }\n\n    .mj-carousel-thumbnail:hover {\n      border-color: #fead0d !important;\n    }\n\n    .mj-carousel-8d0f8a46c6d6-thumbnail-1:hover + .mj-carousel-main .mj-carousel-image-1 {\n      display: block !important;\n    }\n    \n\n      .mj-carousel noinput { display:block !important; }\n      .mj-carousel noinput .mj-carousel-image-1 { display: block !important;  }\n      .mj-carousel noinput .mj-carousel-arrows,\n      .mj-carousel noinput .mj-carousel-thumbnails { display: none !important; }\n\n      @media screen yahoo {\n          .mj-carousel-8d0f8a46c6d6-icons-cell,\n          .mj-carousel-previous-icons,\n          .mj-carousel-next-icons {\n              display: none !important;\n          }\n\n          .mj-carousel-8d0f8a46c6d6-radio-1:checked + .mj-carousel-content .mj-carousel-8d0f8a46c6d6-thumbnail-1 {\n              border-color: transparent;\n          }\n      }\n    \n        \n\n      noinput.mj-accordion-checkbox { display:block!important; }\n\n      @media yahoo, only screen and (min-width:0) {\n        .mj-accordion-element { display:block; }\n        input.mj-accordion-checkbox, .mj-accordion-less { display:none!important; }\n        input.mj-accordion-checkbox + * .mj-accordion-title { cursor:pointer; touch-action:manipulation; -webkit-user-select:none; -moz-user-select:none; user-select:none; }\n        input.mj-accordion-checkbox + * .mj-accordion-content { overflow:hidden; display:none; }\n        input.mj-accordion-checkbox + * .mj-accordion-more { display:block!important; }\n        input.mj-accordion-checkbox:checked + * .mj-accordion-content { display:block; }\n        input.mj-accordion-checkbox:checked + * .mj-accordion-more { display:none!important; }\n        input.mj-accordion-checkbox:checked + * .mj-accordion-less { display:block!important; }\n      }\n\n      .moz-text-html input.mj-accordion-checkbox + * .mj-accordion-title { cursor: auto; touch-action: auto; -webkit-user-select: auto; -moz-user-select: auto; user-select: auto; }\n      .moz-text-html input.mj-accordion-checkbox + * .mj-accordion-content { overflow: hidden; display: block; }\n      .moz-text-html input.mj-accordion-checkbox + * .mj-accordion-ico { display: none; }\n\n      @goodbye { @gmail }\n    \n\n      noinput.mj-menu-checkbox { display:block!important; max-height:none!important; visibility:visible!important; }\n\n      @media only screen and (max-width:320px) {\n        .mj-menu-checkbox[type=\"checkbox\"] ~ .mj-inline-links { display:none!important; }\n        .mj-menu-checkbox[type=\"checkbox\"]:checked ~ .mj-inline-links,\n        .mj-menu-checkbox[type=\"checkbox\"] ~ .mj-menu-trigger { display:block!important; max-width:none!important; max-height:none!important; font-size:inherit!important; }\n        .mj-menu-checkbox[type=\"checkbox\"] ~ .mj-inline-links > a { display:block!important; }\n        .mj-menu-checkbox[type=\"checkbox\"]:checked ~ .mj-menu-trigger .mj-menu-icon-close { display:block!important; }\n        .mj-menu-checkbox[type=\"checkbox\"]:checked ~ .mj-menu-trigger .mj-menu-icon-open { display:none!important; }\n      }\n    \n        </style>\n        \n        \n      </head>\n      <body style=\"word-spacing:normal;\">\n        \n    <div style=\"display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;\">\n      <mj-include path=\"./mj-include_allowed.mjml\" />\n\t\t\tIpsum\n    </div>\n  \n        \n      <div\n         style=\"\"\n      >\n        \n      \n      \n    \n      \n      <div  style=\"margin:0px auto;max-width:600px;\">\n        \n        <table\n           align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\"\n        >\n          <tbody>\n            <tr>\n              <td\n                 style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;\"\n              >\n                \n            \n      <div\n         class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\"\n      >\n        \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\"\n      >\n        <tbody>\n          \n              <tr>\n                <td\n                   style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         cell-spacing=\"0\" cell-padding=\"0\" class=\"mj-accordion\" style=\"width:100%;border-collapse:collapse;border:2px solid black;border-bottom:none;font-family:Ubuntu, Helvetica, Arial, sans-serif;\"\n      >\n        <tbody>\n          \n      <tr\n        \n      >\n        <td  style=\"padding:0px;\">\n          <label\n             class=\"mj-accordion-element\" style=\"font-size:13px;\"\n          >\n            \n    <input class=\"mj-accordion-checkbox\" type=\"checkbox\" style=\"display:none;\" />\n  \n            <div>\n              \n      <div  class=\"mj-accordion-title\">\n        <table\n           cell-spacing=\"0\" cell-padding=\"0\" style=\"width:100%;border-bottom:2px solid black;\"\n        >\n          <tbody>\n            <tr>\n              \n      <td\n         style=\"width:100%;font-size:13px;padding:16px;\"\n      >\n        <mj-include path=\"./mj-include_allowed.mjml\" />\n      </td>\n    \n\n    <td class=\"mj-accordion-ico\" style=\"padding:16px;vertical-align:middle;\" ><img src=\"https://i.imgur.com/bIXv1bk.png\" alt=\"+\" class=\"mj-accordion-more\" style=\"display:none;width:32px;height:32px;\" /><img src=\"https://i.imgur.com/w4uTygT.png\" alt=\"-\" class=\"mj-accordion-less\" style=\"display:none;width:32px;height:32px;\" /></td>\n  \n            </tr>\n          </tbody>\n        </table>\n      </div>\n    \n      <div\n         class=\"mj-accordion-content\"\n      >\n        <table\n           cell-spacing=\"0\" cell-padding=\"0\" style=\"width:100%;border-bottom:2px solid black;\"\n        >\n          <tbody>\n            <tr>\n              \n      <td\n         style=\"font-size:13px;line-height:1;padding:16px;\"\n      >\n        <mj-include path=\"./mj-include_allowed.mjml\" />\n      </td>\n    \n            </tr>\n          </tbody>\n        </table>\n      </div>\n    \n            </div>\n          </label>\n        </td>\n      </tr>\n    \n        </tbody>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" style=\"font-size:0px;word-break:break-word;\"\n                >\n                  \n      \n    \n    \n        <div\n           class=\"mj-carousel\"\n        >\n          \n      <input\n         class=\"mj-carousel-radio mj-carousel-8d0f8a46c6d6-radio mj-carousel-8d0f8a46c6d6-radio-1\" checked=\"checked\" type=\"radio\" name=\"mj-carousel-radio-8d0f8a46c6d6\" id=\"mj-carousel-8d0f8a46c6d6-radio-1\" style=\"display:none;mso-hide:all;\"\n      />\n    \n          <div\n             class=\"mj-carousel-content mj-carousel-8d0f8a46c6d6-content\" style=\"display:table;width:100%;table-layout:fixed;text-align:center;font-size:0px;\"\n          >\n            \n      <a\n         style=\"border:2px solid transparent;border-radius:6px;display:inline-block;overflow:hidden;width:110px;\" href=\"#1\" target=\"_blank\" class=\"mj-carousel-thumbnail mj-carousel-8d0f8a46c6d6-thumbnail mj-carousel-8d0f8a46c6d6-thumbnail-1 \"\n      >\n        <label  for=\"mj-carousel-8d0f8a46c6d6-radio-1\">\n          <img\n             style=\"display:block;width:100%;height:auto;\" src=\"https://via.placeholder.com/200\" width=\"110\"\n          />\n        </label>\n      </a>\n    \n            \n      <table\n         style=\"caption-side:top;display:table-caption;table-layout:fixed;width:100%;\" border=\"0\" cell-padding=\"0\" cell-spacing=\"0\" width=\"100%\" role=\"presentation\" class=\"mj-carousel-main\"\n      >\n        <tbody>\n          <tr>\n            \n      <td\n         class=\"mj-carousel-8d0f8a46c6d6-icons-cell\" style=\"font-size:0px;display:none;mso-hide:all;padding:0px;\"\n      >\n        <div\n           class=\"mj-carousel-previous-icons\" style=\"display:none;mso-hide:all;\"\n        >\n          \n              <label\n                 for=\"mj-carousel-8d0f8a46c6d6-radio-1\" class=\"mj-carousel-previous mj-carousel-previous-1\"\n              >\n                <img\n                   src=\"https://i.imgur.com/xTh3hln.png\" alt=\"previous\" style=\"display:block;width:44px;height:auto;\" width=\"44\"\n                />\n              </label>\n            \n        </div>\n      </td>\n    \n            \n      <td\n         style=\"padding:0px;\"\n      >\n        <div\n           class=\"mj-carousel-images\"\n        >\n          \n      <div\n         class=\"mj-carousel-image mj-carousel-image-1 \" style=\"\"\n      >\n        \n      <img\n         src=\"https://via.placeholder.com/200\" style=\"border-radius:6px;display:block;width:600px;max-width:100%;height:auto;\" width=\"600\" border=\"0\" />\n    \n      </div>\n    \n        </div>\n      </td>\n    \n            \n      <td\n         class=\"mj-carousel-8d0f8a46c6d6-icons-cell\" style=\"font-size:0px;display:none;mso-hide:all;padding:0px;\"\n      >\n        <div\n           class=\"mj-carousel-next-icons\" style=\"display:none;mso-hide:all;\"\n        >\n          \n              <label\n                 for=\"mj-carousel-8d0f8a46c6d6-radio-1\" class=\"mj-carousel-next mj-carousel-next-1\"\n              >\n                <img\n                   src=\"https://i.imgur.com/os7o9kz.png\" alt=\"next\" style=\"display:block;width:44px;height:auto;\" width=\"44\"\n                />\n              </label>\n            \n        </div>\n      </td>\n    \n          </tr>\n        </tbody>\n      </table>\n    \n          </div>\n        </div>\n      \n    \n  \n      \n    \n  \n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" style=\"font-size:0px;word-break:break-word;\"\n                >\n                  \n        \n      \n    \n    \n        <input type=\"checkbox\" id=\"5f9d353b4ca21581\" class=\"mj-menu-checkbox\" style=\"display:none !important; max-height:0; visibility:hidden;\" />\n      \n    \n  \n      <div\n         class=\"mj-menu-trigger\" style=\"display:none;max-height:0px;max-width:0px;font-size:0px;overflow:hidden;\"\n      >\n        <label\n           for=\"5f9d353b4ca21581\" class=\"mj-menu-label\" style=\"display:block;cursor:pointer;mso-hide:all;-moz-user-select:none;user-select:none;color:#ffffff;font-size:30px;font-family:Ubuntu, Helvetica, Arial, sans-serif;text-transform:uppercase;text-decoration:none;line-height:30px;padding:10px;\" align=\"center\"\n        >\n          <span\n             class=\"mj-menu-icon-open\" style=\"mso-hide:all;\"\n          >\n            &#9776;\n          </span>\n          <span\n             class=\"mj-menu-icon-close\" style=\"display:none;mso-hide:all;\"\n          >\n            &#8855;\n          </span>\n        </label>\n      </div>\n    \n        <div\n           class=\"mj-inline-links\" style=\"\"\n        >\n        \n    \n  \n        \n      <a\n         class=\"mj-link\" href=\"https://mjml.io/jumpTarget\" target=\"_blank\" style=\"display:inline-block;color:#000000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:22px;text-decoration:none;text-transform:uppercase;padding:15px 10px;\"\n      >\n        <mj-include path=\"./mj-include_allowed.mjml\" />\n\t\t\t\t\t\tnavbar-link Jump\n      </a>\n    \n        \n    \n  \n        </div>\n    \n                </td>\n              </tr>\n            <mj-include path=\"./mj-include_allowed.mjml\" />\n\t\t\t\t\t<p>ipsum</p>\n              <tr>\n                <td\n                   align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      \n     \n              <table\n                 align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"float:none;display:inline-table;\"\n              >\n                \n      <tr\n        \n      >\n        <td  style=\"padding:4px;vertical-align:middle;\">\n          <table\n             border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#3b5998;border-radius:3px;width:20px;\"\n          >\n            <tr>\n              <td  style=\"font-size:0;height:20px;vertical-align:middle;width:20px;\">\n                <a  href=\"https://www.facebook.com/sharer/sharer.php?u=https://mjml.io/\" target=\"_blank\">\n                    <img\n                       height=\"20\" src=\"https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png\" style=\"border-radius:3px;display:block;\" width=\"20\"\n                    />\n                  </a>\n                </td>\n              </tr>\n          </table>\n        </td>\n        \n          <td  style=\"vertical-align:middle;\">\n            <a\n                 href=\"https://www.facebook.com/sharer/sharer.php?u=https://mjml.io/\" style=\"color:#333333;font-size:13px;font-family:Ubuntu, Helvetica, Arial, sans-serif;line-height:22px;text-decoration:none;\" target=\"_blank\">\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n\t\t\t\t\t\tFacebook\n            </a>\n          </td>\n          \n      </tr>\n    \n              </table>\n            \n    \n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            \n              <tr>\n                <td\n                   align=\"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\"\n                >\n                  \n      <table\n         border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\"\n      >\n        <tr>\n          <td\n             align=\"center\" bgcolor=\"#414141\" role=\"presentation\" style=\"border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#414141;\" valign=\"middle\"\n          >\n            <p\n               style=\"display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;\"\n            >\n              <mj-include path=\"./mj-include_allowed.mjml\" />\n            </p>\n          </td>\n        </tr>\n      </table>\n    \n                </td>\n              </tr>\n            <p id=\"jumpTarget\"></p>\n        </tbody>\n      </table>\n    \n      </div>\n    \n          \n              </td>\n            </tr>\n          </tbody>\n        </table>\n        \n      </div>\n    \n      \n      \n    \n    \n      </div>\n    \n      </body>\n    </html>\n  ","errors":[{"line":13,"message":"Element mj-s doesn't exist or is not registered","tagName":"mj-s","formattedMessage":"Line 13 of C:\\dev\\clones\\email\\qd (mj-s) â€” Element mj-s doesn't exist or is not registered"},{"line":13,"message":"mj-button cannot be used inside mj-head, only inside: mj-attributes, mj-column, mj-hero","tagName":"mj-button","formattedMessage":"Line 13 of C:\\dev\\clones\\email\\qd\\mj-include_allowed.mjml, included at line 14 of file C:\\dev\\clones\\email\\qd (mj-button) â€” mj-button cannot be used inside mj-head, only inside: mj-attributes, mj-column, mj-hero"}]}
> 
> com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
>  at [Source: (String)"No matching component for tag : mj-s
> {"html":"\n    <!doctype html>\n    <html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com🏢office\">\n      <head>\n        <title>\n          \n        </title>\n        \n        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n        \n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n        <meta name=\"v"[truncated 27871 chars]; line: 1, column: 3]
>     at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1922)
>     at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:720)
>     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2903)
>     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2881)
>     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2662)
>     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1926)
>     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:781)
>     at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4682)
>     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4584)
>     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
>     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
>     at de.timo_reymann.mjml_support.editor.render.MjmlRenderer.parseResult(MjmlRenderer.kt:83)
>     at de.timo_reymann.mjml_support.editor.render.MjmlRenderer.render(MjmlRenderer.kt:115)
>     at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditor.updateHtml(MjmlPreviewFileEditor.kt:154)
>     at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditor.access$updateHtml(MjmlPreviewFileEditor.kt:53)
>     at de.timo_reymann.mjml_support.editor.MjmlPreviewFileEditor$1$documentChanged$1.run(MjmlPreviewFileEditor.kt:276)
>     at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
>     at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
>     at com.intellij.util.Alarm$Request.run(Alarm.java:355)
>     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>     at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
>     at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
>     at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
>     at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
>     at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
>     at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>     at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
>     at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
>     at java.base/java.security.AccessController.doPrivileged(Native Method)
>     at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
>     at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by timo-reymann** [comment]
First analysis:

- Ignoring stderr seems to work just fine!
- Output then looks like this:
![image](https://user-images.githubusercontent.com/21024948/123479006-93073800-d600-11eb-9d6a-729a3a2e562d.png)

**Comment by timo-reymann** [comment]
Interesting side note: com.intellij.execution.process.ProcessAdapter#onTextAvailable contains the outputType that indicates if the output is stdout, stderr or system. A very useful information that also makes it obsolete to skip the first line that is simply the command to execute.
