### ISSUE TITLE
IDE Fatal Error when multiple instances of WebStorm are starting

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#37]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Windows 10 Home Edition 20H2 19042.1052 (current)
* WebStorm 2021.1.3 #WS-211.7628.25, built on June 30, 2021
* MJML Support 2021.06.29-307

## Problem description

IDE Fatal Error

```
java.nio.file.FileSystemException: C:\...\JetBrains\WebStorm2021.1\plugins\mjml-support\renderer.zip: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
	at java.base/java.nio.file.Files.copy(Files.java:3130)
	at de.timo_reymann.mjml_support.util.FilePluginUtil.copyFile(FilePluginUtil.kt:18)
	at de.timo_reymann.mjml_support.editor.render.BuiltinRenderResourceProvider.copyResources(BuiltinRenderResourceProvider.kt:22)
	at de.timo_reymann.mjml_support.editor.MjmlPreviewStartupActivity$runActivity$1.run(MjmlPreviewStartupActivity.kt:17)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Important Factoids

This exception occurred on an instance of WebStorm open to my fork of this Kotlin project. I had slightly changed one string value and committed when I noticed a notification the WebStorm 2021.1.3 was available. Another instance of WebStorm (another window) was open.

I allowed WebStorm to restart. Both instances of WebStorm restarted. The above exception occurred on the restart.

**Comment by timo-reymann** [comment]
relates to #34 

Should be fixed with new snapshot version :)

**Comment by timo-reymann** [comment]
I will close this for more clarity. If it doesnt work as expected with the new snapshot (available approx. on 5.07) feel free to comment on the older ticket :)

**Comment by GarryFlemings** [comment]
I repeated the process described in this ticket, this time with MJML Support 2021.07.09-322. No error. Both WebStorm windows opened.
