### ISSUE TITLE
PhpStorm 2021.1 error with MJML Support 1.7.0

### ISSUE THREAD

**Issue by Carobit** [timo-reymann/intellij-mjml-support#8]
Hi, 
Just tried to install (first time) MJML Support 1.7.0 plugin in PhpStorm 2021.1 on Linux 5.10.26-1-manjaro. When a mjml file is opened Phpstorm reports this IDE Fatal Error. The syntax highlighting seems to work but obviously the rendering doesn't. Actually there's no mjml-support in the /opt/phpstorm/plugins directory.

```
java.nio.file.NoSuchFileException: /opt/phpstorm/plugins/mjml-support/renderer.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.copy(Files.java:3142)
	at de.timo_reymann.mjml_support.util.FilePluginUtil.copyFile(FilePluginUtil.kt:17)
	at de.timo_reymann.mjml_support.editor.MjmlPreviewStartupActivity.runActivity(MjmlPreviewStartupActivity.kt:14)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:245)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by timo-reymann** [comment]
Hi Carobit,

first sorry for the inconvenience with my plugin.

can you verify the folder  _/opt/phpstorm/plugins_ exists and is writable by PHPStorm?
Have you installed PHPStorm via the toolbox or manually?

**Comment by Carobit** [comment]
It's installed through AUR.
https://aur.archlinux.org/packages/phpstorm
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=phpstorm

It happens whenever I open a mjml file even after restarting PhpStorm.

Actually the problem is with the owner/permission. Changing the plugins folder owner fixed the issue, so it's fine now. Maybe I'm wrong but the plugins shouldn't be stored in the idea config directory? I think the /opt folder is a system folder and should have root owner and permission 755.

Maybe a relevant thread:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206601265-Fixed-PyCharm-automatic-update-fails-on-Linux-due-to-permissions
Similarly as this post suggests (for update), adding a plugin as root may cause side effects in the config directory in the home directory (I'm afraid it would make changes as root there).

**Comment by timo-reymann** [comment]
Thank you for the details.

The plugin it self is not stored in the config folder, its just the folder to put persistent stuff for plugins. 
I get this path from IntellIJ, telling me where i can store my stuff: (https://github.com/timo-reymann/intellij-mjml-support/blob/main/src/main/kotlin/de/timo_reymann/mjml_support/util/FilePluginUtil.kt#L12)

Writing to this folder is necessary because the preview uses node.js for rendering and requires some node modules installed, i tried to bundle this or load this directly from the plugin jar but unfortunately there is no way.

So i am afraid there is nothing i can do about it to fix the problem.

**Comment by Carobit** [comment]
Thanks for the information, good to know. Anyway, this workaround (setting owner for plugins dir) works for me, so I guess that's all for now.

**Comment by Ririshi** [comment]
Just a small addition to the thread: this also happens on Windows systems, where the path (for me, currently) is `C:\Program Files (x86)\JetBrains\PhpStorm 2021.1\plugins\mjml-support`. This folder does not exist as the plugin does not have write access.

Manually creating the `mjml-support` folder inside the `plugins` folder, and giving the USERS group access to `write` and `modify` permissions using the Windows permissions interface, will fix the issue. Would be nice if this could be fixed without a manual patch by the user, though.

**Comment by timo-reymann** [comment]
So instead of using the plugins home from the platform sdk i now diretctly use the system path for storing configuration: https://github.com/timo-reymann/intellij-mjml-support/commit/aaabd51f663055aca86e29ceb08bda6d57fed57e

This way its always stored in an user writable location, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
