### ISSUE TITLE
java.lang.Throwable: Assertion failed: Already disposed

### ISSUE THREAD

**Issue by fazzinipierluigi** [timo-reymann/intellij-mjml-support#84]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Windows 10 10.0 (amd64)
* IDE: PhpStorm 2021.2.2 (build PS-212.5284.49)
* Plugin: 1.19.0

#### StackTrace
```
java.lang.Throwable: Assertion failed: Already disposed
at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
at com.intellij.util.Alarm.checkDisposed(Alarm.java:66)
at com.intellij.util.Alarm._addRequest(Alarm.java:213)
at com.intellij.util.Alarm.addRequest(Alarm.java:178)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.updateHtmlPooled(MjmlPreviewFileEditor.kt:357)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.updateHtmlPooled$default(MjmlPreviewFileEditor.kt:355)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.attachHtmlPanel(MjmlPreviewFileEditor.kt:314)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.access$attachHtmlPanel(MjmlPreviewFileEditor.kt:63)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor$3.invokeSuspend(MjmlPreviewFileEditor.kt:415)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor$3.invoke(MjmlPreviewFileEditor.kt)
at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor$3.invoke(MjmlPreviewFileEditor.kt)
at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$4.invokeSuspend(IntrinsicsJvm.kt:205)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by timo-reymann** [comment]
Can you please provide more information how the error occured?
